/**
 * Debug Scenario Fixtures
 * 
 * These JSON files are generated by E2E tests in e2e/generators/
 * Run `npm run generate:scenarios` to regenerate them.
 * 
 * Each fixture is a complete save game state that can be loaded
 * via URL parameter: ?scenario=fresh-start
 */

// Import fixtures
import scenarioFreshStart from './scenario-fresh-start.save.json';
import scenarioPostTutorialPart2 from './scenario-post-tutorial-part-2.save.json';
import scenarioTutorialPart1PriorToSabotage from './scenario-tutorial-part-1-prior-to-sabotage.save.json';

// Export all available scenarios
export const SCENARIO_FIXTURES = {
    'fresh-start': scenarioFreshStart,
    'post-tutorial-part-2': scenarioPostTutorialPart2,
    'tutorial-part-1-prior-to-sabotage': scenarioTutorialPart1PriorToSabotage,
};

/**
 * Get a scenario fixture by name
 * @param {string} name - Scenario name (e.g., 'fresh-start')
 * @returns {object|null} The save game state or null if not found
 */
export const getScenarioFixture = (name) => {
    return SCENARIO_FIXTURES[name] || null;
};

/**
 * Get list of available scenario names
 * @returns {string[]} Array of scenario names
 */
export const getAvailableScenarios = () => {
    return Object.keys(SCENARIO_FIXTURES);
};

export default SCENARIO_FIXTURES;
