/**
 * Debug Scenarios - Pre-configured game states for testing
 *
 * Scenarios are loaded from JSON fixture files generated by E2E tests.
 * Run `npm run generate:scenarios` to regenerate fixtures.
 * 
 * For quick state tweaks (credits, reputation), use the Game State tab in Debug Panel.
 */

import { isDebugMode } from './debugSystem';
import { getScenarioFixture, getAvailableScenarios } from './fixtures';

/**
 * Get all available debug scenarios
 * @returns {object} Map of scenario ID to scenario metadata
 */
export const getDebugScenarios = () => {
  const scenarios = {};
  const available = getAvailableScenarios();

  // Add fixture-based scenarios
  available.forEach(name => {
    const fixture = getScenarioFixture(name);
    if (fixture) {
      scenarios[name] = {
        name: formatScenarioName(name),
        description: getScenarioDescription(name, fixture),
        isFixture: true,
      };
    }
  });

  return scenarios;
};

/**
 * Format scenario name for display
 * @param {string} name - Scenario name (e.g., 'fresh-start')
 * @returns {string} Formatted name (e.g., 'Fresh Start')
 */
const formatScenarioName = (name) => {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

/**
 * Get scenario description from fixture data
 * @param {string} name - Scenario name
 * @param {object} fixture - Fixture data
 * @returns {string} Description
 */
const getScenarioDescription = (name, fixture) => {
  const credits = fixture.bankAccounts?.[0]?.balance ?? 0;
  const messages = fixture.messages?.length ?? 0;
  const licensed = fixture.licensedSoftware?.length ?? 0;

  return `${credits.toLocaleString()} credits, ${messages} messages, ${licensed} licenses`;
};

// Legacy: Keep DEBUG_SCENARIOS for backwards compatibility with existing tests
// This will be populated dynamically from fixtures
export const DEBUG_SCENARIOS = getDebugScenarios();

/**
 * Load a debug scenario from fixture
 * @param {string} scenarioId - Scenario ID (e.g., 'fresh-start')
 * @param {object} gameContext - Game context with setters
 * @returns {boolean} Whether the scenario was loaded successfully
 */
export const loadScenario = (scenarioId, gameContext) => {
  if (!isDebugMode()) {
    console.warn('Debug system only available in development mode');
    return false;
  }

  const fixture = getScenarioFixture(scenarioId);
  if (!fixture) {
    console.error(`Unknown scenario: ${scenarioId}`);
    return false;
  }

  console.log(`🔧 Loading debug scenario: ${scenarioId}`);

  try {
    // Use shared applyGameState to restore all state (same as loadGame)
    gameContext.applyGameState(fixture);

    console.log(`✅ Debug scenario loaded: ${scenarioId}`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to load scenario: ${scenarioId}`, error);
    return false;
  }
};

// Expose to window for browser console access (dev mode only)
if (isDebugMode()) {
  window.debugLoadScenario = (scenarioId, gameContext) => loadScenario(scenarioId, gameContext);
  window.debugScenarios = DEBUG_SCENARIOS;
  window.getDebugScenarios = getDebugScenarios;
}

export default { loadScenario, DEBUG_SCENARIOS, getDebugScenarios };
